# File my_app/docker-compose.yml
version: "3"

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cumbucax
    ports:
      - 5432:5432
